# Generated by Django 4.0.6 on 2022-11-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Department', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_data',
            name='Group',
        ),
        migrations.AddField(
            model_name='employee_data',
            name='Blood_Group',
            field=models.CharField(choices=[('A +ve', 'A +ve'), ('A -ve', 'A -ve'), ('B +ve', 'B +ve'), ('O +ve', 'B +ve'), ('AB +ve', 'B +ve'), ('B -ve', 'B -ve'), ('O -ve', 'B -ve'), ('AB -ve', 'B -ve')], default='A +ve', max_length=6),
        ),
    ]
