# Generated by Django 4.0.6 on 2022-11-23 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Department', '0002_remove_employee_data_group_employee_data_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data',
            name='Blood_Group',
            field=models.CharField(choices=[('A +ve', 'A +ve'), ('A -ve', 'A -ve'), ('B +ve', 'B +ve'), ('O +ve', 'O +ve'), ('AB +ve', 'AB +ve'), ('B -ve', 'B -ve'), ('O -ve', 'O -ve'), ('AB -ve', 'AB -ve')], default='A +ve', max_length=6),
        ),
        migrations.AlterField(
            model_name='leave_data',
            name='Approved_By',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='APPROVED_BY', to='HR_Department.employee_data'),
        ),
        migrations.AlterField(
            model_name='leave_data',
            name='Recommended_Authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RECOMENDED_AYTHORITY', to='HR_Department.employee_data'),
        ),
    ]
