# Generated by Django 4.0.6 on 2023-01-02 06:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Department', '0003_alter_employee_data_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporting_Officer',
            fields=[
                ('Emp_Code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Employee_Name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee_data',
            name='Employee_Name',
        ),
        migrations.AddField(
            model_name='employee_data',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_data',
            name='Emp_Code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_Department.reporting_officer'),
        ),
        migrations.AlterField(
            model_name='leave_data',
            name='Approved_By',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='APPROVED_BY', to='HR_Department.reporting_officer'),
        ),
        migrations.AlterField(
            model_name='leave_data',
            name='Emp_Code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_Department.reporting_officer'),
        ),
        migrations.AlterField(
            model_name='leave_data',
            name='Recommended_Authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RECOMENDED_AYTHORITY', to='HR_Department.reporting_officer'),
        ),
    ]
