# Generated by Django 4.0.6 on 2023-01-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Department', '0004_reporting_officer_remove_employee_data_employee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_data',
            name='Emp_Type',
            field=models.CharField(choices=[('Teaching', 'Teaching'), ('Non_Teaching', 'Non Teaching')], default='Non_Teaching', max_length=15),
        ),
    ]
