# Generated by Django 4.0.6 on 2023-01-02 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Department', '0005_employee_data_emp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_data',
            name='Reporting_Authority',
            field=models.ForeignKey(default='1111', on_delete=django.db.models.deletion.CASCADE, related_name='Reporting_Authority', to='HR_Department.reporting_officer'),
        ),
    ]
