# Generated by Django 4.0.6 on 2023-01-03 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Department', '0006_employee_data_reporting_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_data',
            name='Approved_By',
            field=models.ForeignKey(default='1111', on_delete=django.db.models.deletion.CASCADE, related_name='APPROVED_BY', to='HR_Department.reporting_officer'),
        ),
        migrations.AlterField(
            model_name='leave_data',
            name='Recommended_Authority',
            field=models.ForeignKey(default='1111', on_delete=django.db.models.deletion.CASCADE, related_name='RECOMENDED_AYTHORITY', to='HR_Department.reporting_officer'),
        ),
    ]
