# Generated by Django 4.0.6 on 2022-08-03 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('Roll_No', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Batch', models.CharField(max_length=5)),
                ('Contect_No', models.BigIntegerField()),
                ('Email_ID', models.EmailField(max_length=254)),
                ('College_Email_ID', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=300)),
                ('DOB', models.DateField()),
                ('Campus', models.CharField(max_length=10)),
                ('Major', models.CharField(max_length=15)),
                ('Minor', models.CharField(max_length=15)),
                ('SSC', models.CharField(max_length=5)),
                ('School', models.CharField(max_length=50)),
                ('HSC', models.CharField(max_length=5)),
                ('Jr_College', models.CharField(max_length=50)),
                ('Graduation', models.CharField(max_length=5)),
                ('Sr_College', models.CharField(max_length=50)),
                ('Graduation_Branch', models.CharField(max_length=25)),
                ('Masters', models.CharField(max_length=5)),
                ('Masters_Branch', models.CharField(max_length=25)),
                ('Masters_University', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_No', models.CharField(max_length=3)),
                ('Roll_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Studentdata.student')),
            ],
        ),
    ]
