# Generated by Django 4.0.6 on 2022-08-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studentdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='Floor',
            field=models.CharField(choices=[('Ground', 'Ground'), ('First', 'First'), ('Second', 'Second')], default='Ground', max_length=6),
        ),
    ]
